# Generated by Django 3.0.2 on 2020-01-31 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='my_artifact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifact_name', models.CharField(max_length=200)),
                ('artifact_images', models.FileField(default='', upload_to='')),
                ('artifact_description', models.CharField(max_length=400)),
                ('artifact_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Price')),
            ],
        ),
    ]
